import {
  card1,
  video1,
  video2,
  video3,
  video4,
  video5,
} from "../assets/images/user";

export const cardsData = [
  {
    id: 1,
    image: card1,
    amount: "$100",
    description: "Basic: how to ride your skateboard comfortly",
    duration: "5",
    views: "50K",
    title: "Andy William",
    watched: true,
    subsType: "pro",
    url: video1,
  },
  {
    id: 2,
    image: card1,
    amount: "10",
    description: "Basic: how to ride your skateboard comfortly",
    duration: "5 ",
    views: "53K",
    title: "Andy William",
    watched: true,
    subscriptionpro: "100k",
    subsType: "free",
    url: video2,
  },
  {
    id: 3,
    image: card1,
    amount: "$0",
    description: "Basic: how to ride your skateboard comfortly",
    duration: "5 ",
    views: "53K",
    title: "Andy William",
    watched: false,
    subsType: "free",
    url: video3,
  },
  {
    id: 4,
    image: card1,
    amount: "$10",
    description: "Basic: how to ride your skateboard comfortly",
    duration: "5",
    views: "53K",
    title: "Andy William",
    watched: false,
    subsType: "free",
    url: video4,
  },
  {
    id: 5,
    image: card1,
    amount: "$300",
    description: "Basic: how to ride your skateboard comfortly",
    duration: "5",
    views: "53K",
    title: "Andy William",
    watched: true,
    subsType: "free",
    url: video5,
  },
  {
    id: 6,
    image: card1,
    amount: "$100",
    description: "Basic: how to ride your skateboard comfortly",
    duration: "5",
    views: "53K",
    title: "Andy William",
    watched: false,
    subsType: "pro",
    url: video1,
  },
  {
    id: 7,
    image: card1,
    amount: "$20",
    description: "Basic: how to ride your skateboard comfortly",
    duration: "5",
    views: "53K",
    title: "Andy William",
    watched: false,
    subsType: "pro",
    url: video5,
  },
  {
    id: 8,
    image: card1,
    amount: "$80",
    description: "Basic: how to ride your skateboard comfortly",
    duration: "5",
    views: "53K",
    title: "Andy William",
    watched: false,
    subsType: "pro",
    url: video2,
  },
  {
    id: 9,
    image: card1,
    amount: "$200",
    description: "Basic: how to ride your skateboard comfortly",
    duration: "5",
    views: "53K",
    title: "Andy William",
    watched: false,
    subsType: "pro",
    url: video3,
  },
  {
    id: 10,
    image: card1,
    amount: "$50",
    description: "Basic: how to ride your skateboard comfortly",
    duration: "5",
    views: "53K",
    title: "Andy William",
    watched: false,
    subsType: "pro",
    url: video4,
  },
  {
    id: 11,
    image: card1,
    amount: "$10",
    description: "Basic: how to ride your skateboard comfortly",
    duration: "5",
    views: "53K",
    title: "Andy William",
    watched: false,
    subsType: "free",
    url: video5,
  },
];
