import {
  User,
  AddProgram,
  Categories,
  Dashboard,
  FaqListing,
  Payment,
  ProgramListing,
  Speaker,
  Tags,
  Faq,
  Login,
  UserList,
  UserDetails,
  AboutUs,
  SocialMedia,
  PrivacyPolicy,
  TermAndConditions,
  Support,
  AddFaq,
} from "../../pages/admin";
import NotFound from "../../pages/common/NotFound";
import { ROUTES } from "../constants";

const {
  adLogin,
  adDashboard,
  adUserDetail,
  adUserList,
  adProgramList,
  adAddprogram,
  adCategories,
  adTags,
  adPayment,
  adSpeaker,
  adFaq,
  adFaqList,
  adAboutUs,
  adSocialLinks,
  adPrivacy,
  adTermConditions,
  adSupport,
  adAddFaq,
  adUpdateProgram,
} = ROUTES;

export const adminRoutes = [
  {
    id: 1,
    type: "public",
    path: adLogin,
    Component: Login,
    Auth: false,
    defaultComp: true,
  },
  {
    id: 1,
    type: "private",
    path: adDashboard,
    Component: Dashboard,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 2,
    type: "private",
    path: adUserList,
    Component: UserList,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 3,
    type: "private",
    path: adUserDetail,
    Component: UserDetails,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 4,
    type: "private",
    path: adProgramList,
    Component: ProgramListing,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 5,
    type: "private",
    path: adAddprogram,
    Component: AddProgram,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 6,
    type: "private",
    path: adCategories,
    Component: Categories,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 7,
    type: "private",
    path: adTags,
    Component: Tags,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 8,
    type: "private",
    path: adPayment,
    Component: Payment,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 9,
    type: "private",
    path: adSpeaker,
    Component: Speaker,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 10,
    type: "private",
    path: adAddFaq,
    Component: AddFaq,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 11,
    type: "private",
    path: adFaqList,
    Component: FaqListing,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 12,
    type: "private",
    path: adAboutUs,
    Component: AboutUs,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 13,
    type: "private",
    path: adSocialLinks,
    Component: SocialMedia,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 14,
    type: "private",
    path: adPrivacy,
    Component: PrivacyPolicy,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 15,
    type: "private",
    path: adTermConditions,
    Component: TermAndConditions,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 16,
    type: "private",
    path: adSupport,
    Component: Support,
    Auth: true,
    defaultComp: false,
  },

  {
    id: 17,
    type: "public",
    path: "*",
    Component: NotFound,
    Auth: false,
    defaultComp: false,
  },

  {
    id: 19,
    type: "private",
    path: adUpdateProgram,
    Component: AddProgram,
    Auth: true,
    defaultComp: false,
  },
];
