import {
  UserListing,
  User,
  AddProgram,
  Categories,
  Dashboard,
  FaqListing,
  Payment,
  ProgramListing,
  Speaker,
  Tags,
  Faq,
} from "../../pages/admin";

export const adminRoutes = [
  {
    id: 1,
    type: "Private",
    path: "/backoffice",
    Component: Dashboard,
    Auth: true,
    defaultComp: true,
  },
  {
    id: 2,
    type: "Private",
    path: "user",
    Component: User,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 3,
    type: "Private",
    path: "user-listing",
    Component: UserListing,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 4,
    type: "Private",
    path: "program-listing",
    Component: ProgramListing,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 5,
    type: "Private",
    path: "add-program",
    Component: AddProgram,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 6,
    type: "Private",
    path: "categories",
    Component: Categories,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 7,
    type: "Private",
    path: "tags",
    Component: Tags,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 8,
    type: "Private",
    path: "payment",
    Component: Payment,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 9,
    type: "Private",
    path: "speaker",
    Component: Speaker,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 10,
    type: "Private",
    path: "faq",
    Component: Faq,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 11,
    type: "Private",
    path: "faq-listing",
    Component: FaqListing,
    Auth: true,
    defaultComp: false,
  },
];
