import {
  User,
  AddProgram,
  Categories,
  Dashboard,
  FaqListing,
  Payment,
  ProgramListing,
  Speaker,
  Tags,
  Faq,
  Login,
  UserList,
  UserDetails,
} from "../../pages/admin";
import { ROUTES } from "../constants";

const {
  adLogin,
  adDashboard,
  adUser,
  adUserList,
  adProgramList,
  adAddprogram,
  adCategories,
  adTags,
  adPayment,
  adSpeaker,
  adFaq,
  adFaqList,
} = ROUTES;

export const adminRoutes = [
  {
    id: 1,
    type: "public",
    path: adLogin,
    Component: Login,
    Auth: false,
    defaultComp: true,
  },
  {
    id: 1,
    type: "private",
    path: adDashboard,
    Component: Dashboard,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 2,
    type: "private",
    path: adUserList,
    Component: UserList,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 3,
    type: "private",
    path: adUser,
    Component: UserDetails,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 4,
    type: "private",
    path: adProgramList,
    Component: ProgramListing,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 5,
    type: "private",
    path: adAddprogram,
    Component: AddProgram,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 6,
    type: "private",
    path: adCategories,
    Component: Categories,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 7,
    type: "private",
    path: adTags,
    Component: Tags,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 8,
    type: "private",
    path: adPayment,
    Component: Payment,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 9,
    type: "private",
    path: adSpeaker,
    Component: Speaker,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 10,
    type: "private",
    path: adFaq,
    Component: Faq,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 11,
    type: "private",
    path: adFaqList,
    Component: FaqListing,
    Auth: true,
    defaultComp: false,
  },
];
