import NotFound from "../../pages/common/NotFound";
import {
  CreateNewPassword,
  Home,
  Login,
  PrivacyPolicy,
  Programs,
  RefundsPolicy,
  ResetPassword,
  TermsofService,
  UserProfile,
  VideoPlayer,
  Signup,
  AboutUs,
  Faq,
  ContactUs,
} from "../../pages/user";
import Otp from "../../pages/user/Otp";
import { ROUTES } from "../constants";

const {
  usrLogin,
  usrPrograms,
  usrResetPassword,
  usrCreatePassword,
  usrOtp,
  usrVideoPlayer,
  usrHome,
  usrPrivacy,
  usrRefundPolicy,
  usrTermCon,
  usrSignUp,
  usrEditProfile,
  usrAboutUs,
  usrContactUs,
  usrFaq,
} = ROUTES;
export const userRoutes = [
  {
    id: 1,
    type: "public",
    path: usrHome,
    Component: Home,
    Auth: false,
    defaultComp: true,
  },
  {
    id: 2,
    type: "public",
    path: usrPrivacy,
    Component: PrivacyPolicy,
    Auth: false,
    defaultComp: false,
  },
  {
    id: 3,
    type: "public",
    path: usrRefundPolicy,
    Component: RefundsPolicy,
    Auth: false,
    defaultComp: false,
  },
  {
    id: 4,
    type: "public",
    path: usrTermCon,
    Component: TermsofService,
    Auth: false,
    defaultComp: false,
  },

  {
    id: 5,
    type: "public",
    path: usrOtp,
    Component: Otp,
    Auth: false,
    defaultComp: false,
  },
  {
    id: 6,
    type: "private",
    path: `${usrVideoPlayer}/:videoId`,
    Component: VideoPlayer,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 7,
    type: "public",
    path: usrLogin,
    Component: Login,
    Auth: false,
    defaultComp: true,
  },
  {
    id: 8,
    type: "public",
    path: usrSignUp,
    Component: Signup,
    Auth: false,
    defaultComp: false,
  },
  {
    id: 9,
    type: "public",
    path: usrCreatePassword,
    Component: CreateNewPassword,
    Auth: false,
    defaultComp: false,
  },
  {
    id: 10,
    type: "public",
    path: usrResetPassword,
    Component: ResetPassword,
    Auth: false,
    defaultComp: false,
  },
  {
    id: 11,
    type: "public",
    path: usrPrograms,
    Component: Programs,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 12,
    type: "private",
    path: usrEditProfile,
    Component: UserProfile,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 13,
    type: "public",
    path: usrAboutUs,
    Component: AboutUs,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 14,
    type: "public",
    path: usrContactUs,
    Component: ContactUs,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 15,
    type: "public",
    path: usrFaq,
    Component: Faq,
    Auth: false,
    defaultComp: false,
  },
  {
    id: 16,
    type: "public",
    path: "*",
    Component: NotFound,
    Auth: false,
    defaultComp: false,
  },
];
