import {
  CreateNewPassword,
  Home,
  Login,
  PrivacyPolicy,
  Programs,
  RefundsPolicy,
  ResetPassword,
  Sigup,
  TermsofService,
  UserProfile,
  VideoPlayer,
  Signup,
} from "../../pages/user";
import Otp from "../../pages/user/Otp";
import { ROUTES } from "../constants";

const { usrLogin, usrPrograms, usrResetPassword, usrCreatePassword, usrOtp } =
  ROUTES;
export const userRoutes = [
  {
    id: 1,
    type: "public",
    path: "/",
    Component: Home,
    Auth: false,
    defaultComp: true,
  },
  {
    id: 2,
    type: "private",
    path: usrPrograms,
    Component: Programs,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 3,
    type: "private",
    path: "videoplayer",
    Component: VideoPlayer,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 4,
    type: "public",
    path: usrLogin,
    Component: Login,
    Auth: false,
    defaultComp: true,
  },
  {
    id: 5,
    type: "private",
    path: "signup",
    Component: Signup,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 6,
    type: "public",
    path: usrResetPassword,
    Component: ResetPassword,
    Auth: false,
    defaultComp: true,
  },
  {
    id: 7,
    type: "public",
    path: usrCreatePassword,
    Component: CreateNewPassword,
    Auth: false,
    defaultComp: true,
  },
  {
    id: 8,
    type: "private",
    path: "edit-profile",
    Component: UserProfile,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 9,
    type: "private",
    path: "privacy-policy",
    Component: PrivacyPolicy,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 10,
    type: "private",
    path: "refunds-policy",
    Component: RefundsPolicy,
    Auth: true,
    defaultComp: false,
  },
  {
    id: 11,
    type: "private",
    path: "terms-of-service",
    Component: TermsofService,
    Auth: true,
    defaultComp: false,
  },

  {
    id: 12,
    type: "public",
    path: usrOtp,
    Component: Otp,
    Auth: false,
    defaultComp: false,
  },
];
