import {
    CreateNewPassword,
    Home,
    Login,
    PrivacyPolicy,
    Programs,
    RefundsPolicy,
    ResetPassword,
    Sigup,
    TermsofService,
    UserProfile,
    VideoPlayer,
    Signup,
  } from "../../pages/user"


  export const userRoutes = [
    {
      id: 1,
      type: "Private",
      path: "/",
      Component: Home,
      Auth: true,
      defaultComp: true,
    },
    {
      id: 2,
      type: "Private",
      path: "Programs",
      Component: Programs,
      Auth: true,
      defaultComp: false,
    },
    {
      id: 3,
      type: "Private",
      path: "videoplayer",
      Component: VideoPlayer,
      Auth: true,
      defaultComp: false,
    },
    {
      id: 4,
      type: "Private",
      path: "login",
      Component: Login,
      Auth: true,
      defaultComp: false,
    },
    {
      id: 5,
      type: "Private",
      path: "signup",
      Component: Signup,
      Auth: true,
      defaultComp: false,
    },
    {
      id: 6,
      type: "Private",
      path: "reset_password",
      Component: ResetPassword,
      Auth: true,
      defaultComp: false,
    },
    {
      id: 7,
      type: "Private",
      path: "create_new_password",
      Component: CreateNewPassword,
      Auth: true,
      defaultComp: false,
    },
    {
      id: 8,
      type: "Private",
      path: "edit-profile",
      Component: UserProfile,
      Auth: true,
      defaultComp: false,
    },
    {
      id: 9,
      type: "Private",
      path: "privacy-policy",
      Component: PrivacyPolicy,
      Auth: true,
      defaultComp: false,
    },
    {
      id: 10,
      type: "Private",
      path: "refunds-policy",
      Component: RefundsPolicy,
      Auth: true,
      defaultComp: false,
    },
    {
      id: 11,
      type: "Private",
      path: "terms-of-service",
      Component: TermsofService,
      Auth: true,
      defaultComp: false,
    },
  ];
  