export const ROUTES = {
  adLogin: "/backoffice",
  adDashboard: "/backoffice/dashboard",
  adUserDetail: "/backoffice/user",
  adUserList: "/backoffice/user-listing",
  adProgramList: "/backoffice/program-listing",
  adAddprogram: "/backoffice/add-program",
  adCategories: "/backoffice/categories",
  adTags: "/backoffice/tags",
  adPayment: "/backoffice/payment",
  adSpeaker: "/backoffice/speaker",
  adFaq: "/backoffice/faq",
  adFaqList: "/backoffice/faq-listing",
  adAboutUs: "/backoffice/about-us",
  adSocialLinks: "/backoffice/social-media-links",
  adPrivacy: "/backoffice/privacy-policy",
  adTermConditions: "/backoffice/terms-and-conditions",
  adSupport: "/backoffice/support",

  // user routes
  usrHome: "/",
  usrLogin: "/login",
  usrPrograms: "/Programs",
  usrResetPassword: "/reset_password",
  usrCreatePassword: "/create_new_password",
  usrOtp: "/otp",
  usrEditProfile: "/edit-profile",
  usrVideoPlayer: "/videoplayer",
};
