export const ROUTES = {
  adLogin: "/backoffice",
  adDashboard: "/backoffice/dashboard",
  adUserDetail: "/backoffice/user",
  adUserList: "/backoffice/user-listing",
  adProgramList: "/backoffice/program-listing",
  adAddprogram: "/backoffice/add-program",
  adCategories: "/backoffice/categories",
  adTags: "/backoffice/tags",
  adPayment: "/backoffice/payment",
  adSpeaker: "/backoffice/speaker",
  adFaq: "/backoffice/faq",
  adFaqList: "/backoffice/faq-listing",
  adAboutUs: "/backoffice/about-us",
  adSocialLinks: "/backoffice/social-media-links",
  adPrivacy: "/backoffice/privacy-policy",
  adTermConditions: "/backoffice/terms-and-conditions",
  adSupport: "/backoffice/support",
  adAddFaq: "/backoffice/add-faq",
  adUpdateProgram: "/backoffice/update-program",

  // user routes
  usrHome: "/",
  usrLogin: "/login",
  usrSignUp: "/signup",
  usrPrograms: "/Programs",
  usrResetPassword: "/reset_password",
  usrCreatePassword: "/reate_new_password",
  usrOtp: "/otp",
  usrEditProfile: "/edit-profile",
  usrVideoPlayer: "/videoplayer",
  usrPrivacy: "/privacy-policy",
  usrRefundPolicy: "/refunds-policy",
  usrTermCon: "/terms-of-service",
  usrSignUp: "/signup",
  usrAboutUs: "/about-us",
  usrContactUs: "/contact-us",
  usrFaq: "/faq",
};
